#!/usr/bin/sh

go get github.com/mewa/wuff

cd $(go env GOPATH)/src/github.com/mewa/wuff

go build -i -o $HOME/.wuff/wuff

cp scripts/exec $HOME/.wuff/exec

echo "Create your config at ~/.wuff/config.hcl"

echo You can now link wuff with the following command
echo ln -s $HOME/.wuff/wuff /usr/bin/wuff && ln -s $HOME/.wuff/exec /usr/bin/runwuff
